var attractors = [
	{name: "lorentz ", 
	 eq: "dx/dt = A(y - x) ; \n dy/dt = x(B - z)-y ; \n dz/dt = xy - Cz ;"},
	{name: "sprott - R",
	 eq: "dx/dt = 0.9 - y ; \n dy/dt = 0.4 + z ; \n dz/dt = xy - z ;"},
	{name: "sprott - K",
	 eq: "dx/dt = xy - z ; \n dy/dt = x - y ; \n dz/dt = x + 0.3z ;"},
	{name: "sprott - B",
	 eq: "dx/dt = yz ; \n dy/dt = x - y ; \n dz/dt = 1 - xy ;"},
	 {name: "unknown",
	 eq: "dx/dt = sin y - z cos 1.8x ; \n dy/dt = z sin 0.71x - cos 1.51y ; \n dz/dt = sin x ;"},
	 {name: "qi - chen",
	 eq: "dx/dt = A(y - x) + yz ; \n dy/dt = Bx + y - xz ; \n dz/dt = xy - Cz ;"},
	 {name: "yu - wang",
	 eq: "dx/dt = A (y - x) ; \n dy/dt = Bx - Cxz ; \n dz/dt = <i>e</i><sup>xy</sup> - 2.5z ;"},
	 {name: "TSUCS - 1",
	 eq: "dx/dt = A(y - x) + Bxz ; \n dy/dt = Cy - xz ; \n dz/dt = Dz + xy - Ex<sup>2</sup> ;"},
	 {name: "hadley",
	 eq: "dx/dt = - Ay<sup>2</sup> - z<sup>2</sup> - Bx + 8B ; \n dy/dt = xy - Cxz - y + D ; \n dz/dt = Cxy + xz - z ;"},
	 {name: "lorentz mod - 2",
	 eq: "dx/dt = Ax + y<sup>2</sup> - z<sup>2</sup> + 9.9A ; \n dy/dt = x(y - 5z) + 1 ; \n dz/dt = -z + x(5y + z) ;"},
	 {name: "nose - hoover",
	 eq: "dx/dt = y ; \n dy/dt = -x + yz ; \n dz/dt = 1.5 - y<sup>2</sup> ;"},
	 {name: "coullet",
	 eq: "dx/dt = y ; \n dy/dt = z ; \n dz/dt = Ax + By + Cz - x<sup>3</sup>  ;"},
	 {name: "rucklidge",
	 eq: "dx/dt = Ax + By - yz ; \n dy/dt = x ; \n dz/dt = y<sup>2</sup> - z ;"},
	 {name: "bouali",
	 eq: "dx/dt = x(A - y) + Bz ; \n dy/dt = -y(1 - x<sup>2</sup>) ; \n dz/dt = -x(C - z) - Dz ;"},
	 {name: "chen - lee",
	 eq: "dx/dt = Ax - yz ; \n dy/dt = By + xz ; \n dz/dt = Cz + xy/3 ;"},
]